tsaiet proposal: Optimizing Traffic Flow with Ford-Fulkerson
yungyuc/nsdhw_23au pull request #140
Opened 2023-11-05 15:55 UTC by tsaiet

---
A good PR should include the following parts:

- [ ] A clear title
- [ ] A meaningful message for PR, as well as its commits
- [ ] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

2023-11-06 14:01 UTC, yungyuc requested changes
Please leave a global comment when you are ready for the next review.

- [x] Remove unneeded changesets from the PR by rebasing.
- [x] Add an entry to link to your project proposal in `project/README.rst`.

2023-11-06 14:01 UTC, yungyuc commented on project/tsaiet/README.rst
> +Ford-Fulkerson is a mathematical tool used to optimize the flow of resources or
Please briefly describe how does Ford-Fulkerson method work.

2023-11-09 02:15 UTC, yungyuc commented
@tsaiet Please address the points as soon as possible.  Find me in the discord nsd channel if you need more interactive discussions.

2023-11-09 15:11 UTC, tsaiet commented
I finish all your requests above!

2023-11-11 13:55 UTC, yungyuc approved these changes
Thanks.

2023-11-11 13:55 UTC, merged