add README.md for proposal first submission
yungyuc/nsdhw_23au pull request #95
Opened 2023-10-22 11:26 UTC by liamlin5566

---
A good PR should include the following parts:

- [ ] A clear title
- [ ] A meaningful message for PR, as well as its commits
- [ ] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

2023-10-23 12:10 UTC, yungyuc requested changes
- [x] Please add an entry in `project/README.rst` to link to your project proposal
- [ ] Use reasonable (e.g., 79-char) line width

2023-10-23 12:10 UTC, yungyuc commented on project/liamlin5566/README.md
> +This project is the implementation of Kernel K-means on image with c++ and python. I will also try to accelerate the computation on GPU by using CUDA if time is enough.
How do you plan to run CI with GPU/CUDA?

2023-10-23 12:10 UTC, yungyuc commented on project/liamlin5566/README.md
> +Kernel k-means is well-known unsupervised clustering algorithm. It will find k cluster centers to represent each group, and assign each data point to its nearest center like traditional k-means. Diff
Please use a reasonable line width so that I can add comment at proper location.  See #91 for an example.

2023-10-23 12:10 UTC, yungyuc commented on project/liamlin5566/README.md
> +Those who want to do segmentation task on image data useful in image processing and computer vision application.
You may elaborate more using layman's words.  It will make your presentation more appealing to non-experts.

2023-10-23 12:10 UTC, yungyuc commented on project/liamlin5566/README.md
> +Week 5 (11/28): Search how to compute on GPU with CUDA.
Writing CUDA code usually takes more than a month.

2023-10-31 13:32 UTC, yungyuc commented
Please do not mark discussions resolved.  It's harder for me to keep track of them.

2023-10-31 13:34 UTC, yungyuc requested changes
When you are ready for me to review again, please add a global comment.

- [ ] How do you plan to run CI for GPU/CUDA?

2023-11-08 11:40 UTC, liamlin5566 commented
> When you are ready for me to review again, please add a global comment. It will also be good if you can resolve the conflict to the `project` branch, although I can handle it myself.
> 
> * [ ]  How do you plan to run CI for GPU/CUDA?
> * [ ]  Add a link to your project github repository.

I currently have no plans to run CI for CUDA

2023-11-09 02:08 UTC, merged