yui0303 proposal: DoSM
yungyuc/nsdhw_23au pull request #98
Opened 2023-10-23 12:58 UTC by yui0303

---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

2023-10-25 00:51 UTC, yungyuc requested changes
- [x] Add an entry in `project/README.rst` pointing to your proposal.
- [ ] Clarify the size of matrices and whether they are dense or sparse.

2023-10-25 00:51 UTC, yungyuc commented on project/yui0303/README.md
> +The diagonal matrix has the property that all of its off-diagonal elements are zero. There are some prospective usages for related users are shown below.
Eigenvalue problems are a big subject.  How large are the matrices you want to solve?  Is it dense or sparse?

2023-10-25 00:51 UTC, yungyuc commented on project/yui0303/src/SystemArchitecture.jpg
I like your diagram.  I don't think the flow is entirely precise but it's a good start.

2023-10-25 00:51 UTC, yungyuc commented on project/yui0303/README.md
> +  - Binding the c++ API with pybind11
It's not easy to write tests before you have the binding ready.  Testing speeds up your development.  Please think about how to make yourself more productive.

2023-10-25 13:29 UTC, yungyuc commented
When you want me to review again, please leave a global comment.  Make sure the branch does not conflict.

2023-10-31 13:25 UTC, yungyuc commented
@yui0303 Please do not resolve comments.  Resolution makes it harder for me to keep track of them.

2023-10-31 13:30 UTC, yungyuc requested changes
- [ ] Remove unnecessary changesets.

2023-10-31 13:30 UTC, yungyuc commented on hw3/.gitignore
Please remove unnecessary changesets from the git history.  Use rebase or a similar way.

2023-10-31 13:30 UTC, yungyuc commented on project/yui0303/README.md
> +
You have not specify how large are the matrices you want to solve.  I do not insist you to include precise information in the proposal.  Please think about it and the information may enrich your presentation.

2023-11-01 12:53 UTC, yui0303 commented on hw3/.gitignore
I have removed unnecessary changesets.

2023-11-01 14:21 UTC, yui0303 commented on project/yui0303/README.md
> +
Thank you for your reply, I now understand what the teacher meant.
My maximum input should be a 100x100 matrix. The reason is shown below:
The (time) complexity of finding eigenvalues and finding eigenvectors are O(n^4) and O(n^3) respectively.
Thus, when the matrix is 100x100, the complexity is approximately 10^8, and this is such a heavy burden for a personal computer.

Hope this reply can satisfy the teacher's question this time.

Note: O(n^4): The iteration loop is O(n) and the complexity of QR is O(n^3)

2023-11-03 13:51 UTC, yungyuc approved these changes
LGTM.  Let me know when you want it to be merged.

2023-11-03 13:51 UTC, yungyuc commented on project/yui0303/README.md
> +
It's a clear description.  Many other things may be derived from the analysis and I trust you will have a good start.

2023-11-03 13:51 UTC, yungyuc commented on project/yui0303/README.md
> +- Week 8 (12/19): Flextime.
Don't mention it.  The more you tell me, the more I will feed back.  Keep doing it.

2023-11-04 11:31 UTC, yui0303 commented
> LGTM. Let me know when you want it to be merged.

Thank you for the review and the suggestion.  I want it to be merged now. 👍

2023-11-04 13:24 UTC, merged

2023-11-05 02:38 UTC, yungyuc commented
@yui0303 I wonder if you have time for the meetup https://sciwork.dev/meetup/2023/1108-nycu this week.  I'd like to know your availability and progress update in the discord channel #nsd.  (Your repository is empty.)